required = [
  "github.com/mailru/easyjson",
  "golang.org/x/tools/cmd/cover",
  "github.com/mattn/goveralls"
]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.1"

[[constraint]]
  name = "bou.ke/monkey"
  version = "1.0.1"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
