required = ["github.com/mailru/easyjson"]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "bou.ke/monkey"
  version = "1.0.1"
